### ISSUE TITLE
Arduino IDE 1.6.8?

### ISSUE THREAD

**Issue by antranapp** [Cheong2K/STM32-Arduino#12]
do you have release date?

**Comment by Cheong2K** [comment]
Testing in progress. Do you have any problem running Arduino IDE 1.6.8 with the Duo board package 0.2.6?

**Comment by antranapp** [comment]
actually I have no problem until now :)

**Comment by Cheong2K** [comment]
There are no issues with using the Arduino IDE 1.6.8 for the Duo, so I close this issue.
