### ISSUE TITLE
Is it possible to run RedBear Duo as BLE controller as well as iBeacon

### ISSUE THREAD

**Issue by quadcodes** [Cheong2K/STM32-Arduino#20]
I'm wondering if it is possible to use RedBear Duo as BLE controller as well as iBeacon at the same time ? What I want to achieve is to listen to the broadcast signal as soon as the device is within ibeacon range.
Further connect to redbear Duo only if user is willing to perform some actions with Duo.
Please guide.

**Comment by Cheong2K** [comment]
Sorry but kindly please send this question to RedBear discussion forum, they will help.
discuss.redbear.cc
